export const PRIMARY_COLOR = "rgba(53, 194, 193, 1)"; // main greenish blue
export const SECONDARY_COLOR = "rgba(100, 149, 237, 1)"; // blue
export const TERTIARY_COLOR = "white";
export const QUATERNARY_COLOR = "black";
export const QUNINARY_COLOR = "rgba(255, 255, 255, 0.5)"; //gray
export const SENARY_COLOR = "#2B2B2B"; //grayish black
export const BACKDROP_COLOR = "rgba(0, 0, 0, 0.3)";

export const BLUE_COLOR = "#6495ED";
export const DISCREET_HEADING_COLOR = QUNINARY_COLOR;

//PLACE_HOLDER_TEXT COLORS
export const PLACE_HOLDER_TEXT_COLOR = QUNINARY_COLOR;

//POST COLORS
export const POST_BCKG_COLOR = "rgba(29,29,29,0.4)";
export const POST_BORDER_COLOR = PRIMARY_COLOR;

export const POST_OPTIONS_ICON_COLOR = QUNINARY_COLOR;
export const POST_LIKE_ACTIVE_COLOR = PRIMARY_COLOR;
export const POST_LIKE_COUNT_ACTIVE_COLOR = TERTIARY_COLOR;
export const POST_LIKE_INACTIVE_COLOR = QUNINARY_COLOR;
export const POST_LIKE_COUNT_INACTIVE_COLOR = QUNINARY_COLOR;
export const POST_DISLIKE_ACTIVE_COLOR = PRIMARY_COLOR;
export const POST_DISLIKE_COUNT_ACTIVE_COLOR = TERTIARY_COLOR;
export const POST_DISLIKE_INACTIVE_COLOR = QUNINARY_COLOR;
export const POST_DISLIKE_COUNT_INACTIVE_COLOR = QUNINARY_COLOR;
export const POST_COMMENT_ICON_COLOR = QUNINARY_COLOR;
export const POST_COMMENT_COUNT_COLOR = QUNINARY_COLOR;
export const POST_BOOKMARK_ICON_COLOR = QUNINARY_COLOR;

export const POST_MEDIA_BADGE_TEXT_COLOR = TERTIARY_COLOR; // the number of items in the media (shown on the top right)
export const POST_MEDIA_BADGE_BCKG_COLOR = "rgba(0, 0, 0, 0.5)"; // the background of the badge

export const POST_TEXT_COLOR = TERTIARY_COLOR;
export const POST_POSTER_NAME_COLOR = TERTIARY_COLOR;
//HEADER COLORS
export const HEADER_COLOR = QUATERNARY_COLOR;
export const HEADER_ICON_COLOR = TERTIARY_COLOR;

//BOTTOM NAVIGATOR COLORS
export const BOTTOM_NAVIGATOR_COLOR = QUATERNARY_COLOR;
export const BOTTOM_NAVIGATOR_ACTIVE_COLOR = PRIMARY_COLOR;
export const BOTTOM_NAVIGATOR_INACTIVE_COLOR = "rgba(53, 194, 193, 0.5)";

//NOTIFICATION BAR
export const NOTIFICATION_BAR_COLOR = QUATERNARY_COLOR;

//POST MEDIA SCROLL
export const POST_MEDIA_SCROLL_BCKG_COLOR = QUATERNARY_COLOR;

//ADD POST
export const ADD_POST_BCKG_COLOR = QUATERNARY_COLOR;
export const CROSS_COLOR = TERTIARY_COLOR;
export const ADD_POST_HEADING_COLOR = TERTIARY_COLOR;
export const ADD_POST_SECONDARY_HEADING_COLOR = SECONDARY_COLOR;
export const ADD_POST_DISCREET_HEADING_COLOR = DISCREET_HEADING_COLOR;
export const ADD_POST_PLACE_HOLDER_TEXT_COLOR = PLACE_HOLDER_TEXT_COLOR;
export const ADD_POST_UPLOAD_MEDIA_ICON_COLOR = PRIMARY_COLOR;
export const ADD_POST_BUTTON_COLOR = PRIMARY_COLOR;
export const ADD_POST_POSTER_NAME_COLOR = TERTIARY_COLOR;
export const ADD_POST_MINI_MEDIA_TILES_COLOR = QUNINARY_COLOR;

//HOME
export const HOME_ICON_BCKG_COLOR = SENARY_COLOR;
export const HOME_ICON_COLOR = PRIMARY_COLOR;
export const HOME_ICON_TEXT_COLOR = TERTIARY_COLOR;
export const HOME_ICON_DISCREET_HEADING_COLOR = DISCREET_HEADING_COLOR;
export const HOME_BCKG_COLOR = QUATERNARY_COLOR;

//CHATS HOME
export const CHATS_HOME_BCKG_COLOR = TERTIARY_COLOR;
