// change log:
// fixed double spacing between names

export const instructor_array : string[][] = 
[['Ahsan Shamim Chaudhri', 'SDSB', 'ACF'],
['Saira Rizwan', 'SDSB', 'ACF'],
['Mahin Moazzam', 'SDSB', 'ACF'],
['Abdul Rauf', 'SDSB', 'ACF'],
['Syed Zain ul Abidin', 'SDSB', 'ACF'],
['Samia Ahmed Ali', 'SDSB', 'ACF'],
['Samia Ahmed Ali', 'SDSB', 'ACF'],
['Huzaima Bukhari', 'SDSB', 'ACF'],
['Huzaima Bukhari', 'SDSB', 'ACF'],
['Syed Mubashir Ali', 'SDSB', 'ACF'],
['Asad Alam', 'SDSB', 'ACF'],
['Maheen Aamir Syed', 'SDSB', 'BUSADM'],
['Ali Qamar', 'SDSB', 'BUSADM'],
['Saqib Ali', 'SDSB', 'BUSADM'],
['Ussama Yaqub', 'SDSB', 'BUSADM'],
['Lukas Albert Paul Werth', 'HSS', 'HSS'],
['Dominic William Esler', 'HSS', 'HSS'],
['Ghazal Asif', 'HSS', 'ANTH&SOC'],
['Rabia Kamal', 'HSS', 'ANTH&SOC'],
['Syeedda Anjum Ara Alvi', 'HSS', 'ANTH&SOC'],
['Ameem Lutfi', 'HSS', 'ANTH&SOC'],
['Lukas Albert Paul Werth', 'HSS', 'ANTH&SOC'],
['Zebunnisa Hamid', 'HSS', 'ANTH&SOC'],
['Maria Amir', 'HSS', 'ANTH&SOC'],
['Khalida Mazhar', 'SSE', 'BIOLOGY'],
['Aishah Bilal', 'SSE', 'BIOLOGY'],
['Muhammad Tariq', 'SSE', 'BIOLOGY'],
['Zaigham Shahzad', 'SSE', 'BIOLOGY'],
['Khurram Bashir', 'SSE', 'BIOLOGY'],
['Muhammad Tariq', 'SSE', 'BIOLOGY'],
['Muhammad Shoaib', 'SSE', 'BIOLOGY'],
['Safee Ullah Chaudhary', 'SSE', 'BIOLOGY'],
['Faiz Ul Hassan Nasim', 'SSE', 'BIOLOGY'],
['Safee Ullah Chaudhary', 'SSE', 'BIOLOGY'],
['Shaper Mirza', 'SSE', 'BIOLOGY'],
['Muhammad Shoaib', 'SSE', 'BIOLOGY'],
['Muhammad Ahsan Rana', 'SDSB', 'BUSADM'],
['Ghazal Mir Zulfiqar', 'SDSB', 'BUSADM'],
['Ayesha Masood', 'SDSB', 'BUSADM'],
['Anjum Fayyaz', 'SDSB', 'BUSADM'],
['Misbah Tanveer Chaudhry', 'SDSB', 'BUSADM'],
['Faheem Hassan Akhtar', 'SSE', 'CHEMISTRY'],
['Irshad Hussain', 'SSE', 'CHEMISTRY'],
['Qasim Imtiaz', 'SSE', 'CHEMISTRY'],
['Rofice Dickson', 'SSE', 'CHEMISTRY'],
['Ali Rauf', 'SSE', 'CHEMISTRY'],
['Tauqeer Abbas', 'SSE', 'CHEMISTRY'],
['Shahana Khurshid', 'SSE', 'CHEMISTRY'],
['Salman Noshear Arshad', 'SSE', 'CHEMISTRY'],
['Shahana Khurshid', 'SSE', 'CHEMISTRY'],
['Qandeel Almas', 'SSE', 'CHEMISTRY'],
['Tauqeer Abbas', 'SSE', 'CHEMISTRY'],
['Basit Yameen', 'SSE', 'CHEMISTRY'],
['Habib-ur- Rehman', 'SSE', 'CHEMISTRY'],
['Muhammad Saeed', 'SSE', 'CHEMISTRY'],
['Falak Sher', 'SSE', 'CHEMISTRY'],
['Salman Noshear Arshad', 'SSE', 'CHEMISTRY'],
['Muhammad Zaheer', 'SSE', 'CHEMISTRY'],
['Rahman Shah Zaib Saleem', 'SSE', 'CHEMISTRY'],
['Irshad Hussain', 'SSE', 'CHEMISTRY'],
['Habib-ur- Rehman', 'SSE', 'CHEMISTRY'],
['Falak Sher', 'SSE', 'CHEMISTRY'],
['Basit Yameen', 'SSE', 'CHEMISTRY'],
['Ghayoor Abbas Chotana', 'SSE', 'CHEMISTRY'],
['Zahid Hussain', 'HSS', 'HSS'],
['Usama Mumtaz Lali', 'HSS', 'HSS'],
['Fatima Fayyaz', 'HSS', 'HSS'],
['Zia ul Hassan', 'HSS', 'HSS'],
['Raja Mohammad Tabish Habib', 'HSS', 'HSS'],
['Bilal Tanweer', 'HSS', 'HSS'],
['Nasir Abbas', 'HSS', 'HSS'],
['Ghulam Moeenuddin Nizami', 'HSS', 'HSS'],
['Maryam Wasif Khan', 'HSS', 'HSS'],
['Muhammad Fareed Zaffar', 'SSE', 'CS'],
['Muhammad Sohaib Ayub', 'SSE', 'CS'],
['Shafay Shamail', 'SSE', 'CS'],
['Ghufran Baig', 'SSE', 'CS'],
['Ihsan Ayyub Qazi', 'SSE', 'CS'],
['Malik Jahan Khan', 'SSE', 'CS'],
['Muhammad Jahangir Ikram', 'SSE', 'CS'],
['Muhammad Jahangir Ikram', 'SSE', 'CS'],
['Waqar Ahmad', 'SSE', 'CS'],
['Imdad ullah khan', 'SSE', 'CS'],
['Shahid Masud', 'SSE', 'CS'],
['Mian Muhammad Awais', 'SSE', 'CS'],
['Muhammad Tahir', 'SSE', 'CS'],
['Mobin Javed', 'SSE', 'CS'],
['Maryam Abdul Ghafoor', 'SSE', 'CS'],
['Suleman Shahid', 'SSE', 'CS'],
['Basit Shafiq', 'SSE', 'CS'],
['Naveed Ul Hassan', 'SSE', 'CS'],
['Zartash Afzal Uzmi', 'SSE', 'CS'],
['Zafar Ayyub Qazi', 'SSE', 'CS'],
['Murtaza Taj', 'SSE', 'CS'],
['Mobin Javed', 'SSE', 'CS'],
['Muhammad Faryad', 'SSE', 'CS'],
['Agha Ali Raza', 'SSE', 'CS'],
['Mian Muhammad Awais', 'SSE', 'CS'],
['Momin Ayub Uppal', 'SSE', 'CS'],
['Maryam Mustafa', 'SSE', 'CS'],
['Nadeem Ahmad Khan', 'SSE', 'CS'],
['Naveed Anwar Bhatti', 'SSE', 'CS'],
['Muhammad Hamad Alizai', 'SSE', 'CS'],
['Mahira Ilyas', 'SDSB', 'ACF'],
['Humbal Tariq', 'SDSB', 'ACF'],
['Maryam Shah', 'SDSB', 'ACF'],
['Muhammad Asim', 'SDSB', 'ACF'],
['Muhammad Adeel Zaffar', 'SDSB', 'ACF'],
['Raja Usman Khalid', 'SDSB', 'BUSADM'],
['Sheikh Attique Ur Rehman', 'SDSB', 'BUSADM'],
['Raja Usman Khalid', 'SDSB', 'ACF'],
['Sheikh Attique Ur Rehman', 'SDSB', 'ACF'],
['Kamran Rashid', 'SDSB', 'ACF'],
['Kamran Rashid', 'SDSB', 'ACF'],
['Muhammad Abdur Rahman Malik', 'SDSB', 'ACF'],
['Ussama Yaqub', 'SDSB', 'BUSADM'],
['Ahmed Majeed Khan', 'SDSB', 'BUSADM'],
['Tabjeel Ashraf', 'SDSB', 'ACF'],
['Maheen Aamir Syed', 'SDSB', 'ACF'],
['Muhammad Adeel Zaffar', 'SDSB', 'MGMTSCI'],
['Muhammad Ghufran Ahmad', 'SDSB', 'MGMTSCI'],
['Nadia Mukhtar Sayed', 'HSS', 'ECON'],
['Ayesha Karim Malik', 'HSS', 'ECON'],
['Verda Arif', 'HSS', 'ECON'],
['Sher Afghan Asad', 'HSS', 'ECON'],
['Hana Zahir', 'HSS', 'ECON'],
['Anum Fatima', 'HSS', 'ECON'],
['Eeman Shahzad Shahzad Qureshi', 'HSS', 'ECON'],
['Kashif Zaheer Malik', 'HSS', 'ECON'],
['Mohammad Usman Khan', 'HSS', 'ECON'],
['Khalid Mir', 'HSS', 'ECON'],
['Fahd Ali', 'HSS', 'ECON'],
['Mushtaq Ahmad Khan', 'HSS', 'ECON'],
['Ayesha Ali', 'HSS', 'ECON'],
['Farah Said', 'HSS', 'ECON'],
['Daniyal Khan', 'HSS', 'ECON'],
['Antonio Marasco', 'HSS', 'ECON'],
['Rimsha Arif', 'HSS', 'ECON'],
['Usman Elahi', 'HSS', 'ECON'],
['Adeel Tariq', 'HSS', 'ECON'],
['Lyyla Khalid', 'HSS', 'ECON'],
['Lyyla Khalid', 'HSS', 'ECON'],
['Hadia Majid', 'HSS', 'ECON'],
['Sheraz Latif Malik', 'HSS', 'ECON'],
['Daud Ahmed Dard', 'HSS', 'ECON'],
['Syed Ali Hasanain', 'HSS', 'ECON'],
['Yushma Umar', 'HSS', 'ECON'],
['Rabia Khan', 'HSS', 'ECON'],
['Muhammad Farooq Naseer', 'HSS', 'ECON'],
['Rabia Khan', 'HSS', 'ECON'],
['Jasir Shahbaz', 'HSS', 'ECON'],
['Abid Aman Burki', 'HSS', 'ECON'],
['Muhammad Raza Mustafa Khan', 'HSS', 'ECON'],
['Sher Afghan Asad', 'HSS', 'ECON'],
['Osama Khan', 'HSS', 'ECON'],
['Nazish Afraz', 'HSS', 'ECON'],
['Ijaz Nabi', 'HSS', 'ECON'],
['S.M. Turab Hussain', 'HSS', 'ECON'],
['Syed Zahid Ali', 'HSS', 'ECON'],
['Tania Saeed', 'EDU', 'DOE'],
['Hasham Nasir', 'EDU', 'DOE'],
['Sannia Hussain', 'EDU', 'DOE'],
['Fizza Suhail', 'EDU', 'DOE'],
['Syed Farah', 'EDU', 'DOE'],
['Razia Iram Sadik', 'EDU', 'DOE'],
['Aaishay Haque', 'EDU', 'DOE'],
['Jessica Albrent', 'EDU', 'DOE'],
['Mariam Haider', 'EDU', 'DOE'],
['Mehreen Noon', 'EDU', 'DOE'],
['Gulab Khan', 'EDU', 'DOE'],
['Daniyal Yousaf', 'EDU', 'DOE'],
['Soufia Anis Siddiqi', 'EDU', 'DOE'],
['Hasham Nasir', 'EDU', 'DOE'],
['Bilal Ahsan Malik', 'EDU', 'DOE'],
['Farah Nadeem', 'EDU', 'DOE'],
['Ahmad Ayub', 'EDU', 'DOE'],
['Soufia Anis Siddiqi', 'EDU', 'DOE'],
['Razia Iram Sadik', 'EDU', 'DOE'],
['Tayyaba Tamim', 'EDU', 'DOE'],
['Ahmad Ayub', 'EDU', 'DOE'],
['Atif Rahim Khan', 'EDU', 'DOE'],
['Muhammad Ali Siddiqi', 'SSE', 'EE'],
['Hassan Abbas Khan', 'SSE', 'EE'],
['Muhammad Imran Cheema', 'SSE', 'EE'],
['Naveed Ul Hassan', 'SSE', 'EE'],
['Nauman Ahmad Zaffar', 'SSE', 'EE'],
['Hassan Jaleel', 'SSE', 'EE'],
['Faheel Ather Hashmi', 'SSE', 'EE'],
['Hafsa Qamar', 'SSE', 'EE'],
['Raheel Zafar', 'SSE', 'EE'],
['Hassan Jaleel', 'SSE', 'EE'],
['Mudassar Ejaz', 'SSE', 'EE'],
['Muhammad Imran Cheema', 'SSE', 'EE'],
['Muhammad Adeel Ahmed Pasha', 'SSE', 'EE'],
['Shahid Masud', 'SSE', 'EE'],
['Nauman Zafar Butt', 'SSE', 'EE'],
['Syed Muhammad Ahsan Razvi', 'SSE', 'EE'],
['Hassan Mohy-ud-Din', 'SSE', 'EE'],
['Muhammad Junaid Ashraf', 'SDSB', 'BUSADM'],
['Muhammad Shakeel Sadiq Jajja', 'SDSB', 'BUSADM'],
['Jawad Sarwar Naqvi Syed', 'SDSB', 'BUSADM'],
['Ghulam Ali Arain', 'SDSB', 'BUSADM'],
['Choudhry Tanveer Shehzad', 'SDSB', 'BUSADM'],
['Bushra Naqvi', 'SDSB', 'BUSADM'],
['Ehsan Ul Haque', 'SDSB', 'BUSADM'],
['Ehsan Ul Haque', 'SDSB', 'BUSADM'],
['Muhammad Sabieh Anwar', 'SSE', 'ENGG'],
['Ammar Ahmed Khan', 'SSE', 'ENGG'],
['Qasim Imtiaz', 'SSE', 'ENGG'],
['Furrukh A. Khan', 'HSS', 'ENGL'],
['Saba Pirzadeh', 'HSS', 'ENGL'],
['Younis Bin Azeem', 'HSS', 'ENGL'],
['Furrukh A. Khan', 'HSS', 'ENGL'],
['Tom Edward Sewel', 'HSS', 'ENGL'],
['Farah Hasan Ali', 'HSS', 'ENGL'],
['Maryam Ibrahim', 'HSS', 'HSS'],
['Sana Khosa', 'HSS', 'ENV'],
['Hassan Haider Karrar', 'HSS', 'ENV'],
['Talha Manzoor', 'HSS', 'ENV'],
['Asad Farooq', 'HSS', 'ENV'],
['Bushra Naqvi', 'SDSB', 'ACF'],
['Zainab Mehmood', 'SDSB', 'ACF'],
['Salman Khan', 'SDSB', 'ACF'],
['Syed Hashim Mahmood Ali', 'SDSB', 'ACF'],
['Ferhana Ahmed', 'SDSB', 'ACF'],
['Talha Farrukh', 'SDSB', 'ACF'],
['Syed Hashim Mahmood Ali', 'SDSB', 'ACF'],
['Samir Ahmed', 'SDSB', 'ACF'],
['Nauman Afzal Cheema', 'SDSB', 'ACF'],
['Fazal Jawad Seyyed', 'SDSB', 'ACF'],
['Adnan Khan', 'SDSB', 'ACF'],
['Syed Kumail Abbas Rizvi', 'SDSB', 'ACF'],
['Syed Kumail Abbas Rizvi', 'SDSB', 'MGMTSCI'],
['Mohammad Khalil', 'SDSB', 'BUSADM'],
['Ferhana Ahmed', 'SDSB', 'BUSADM'],
['Samir Ahmed', 'SDSB', 'BUSADM'],
['Hui Qi', 'LAW', 'LAW'],
['Syed Hassan Raza', 'LAW', 'LAW'],
['Nida Yasmeen Kirmani', 'HSS', 'SWGI'],
['Waqar Zaidi', 'HSS', 'HISTORY'],
['Ilyas Ahmad Chattha', 'HSS', 'HISTORY'],
['Ali Usman Qasmi', 'HSS', 'HISTORY'],
['Jahanzeb Baloch', 'HSS', 'HISTORY'],
['Nadhra Shahbaz Naeem Khan', 'HSS', 'HISTORY'],
['Muhammad Ali Raza', 'HSS', 'HSS'],
['Muhammad Azfar Nisar', 'SDSB', 'BUSADM'],
['Hafiz Abdul Qadeer', 'HSS', 'GC'],
['Zahid Hussain', 'HSS', 'GC'],
['Hafiz Abdul Qadeer', 'HSS', 'GC'],
['Muhammad Iftikhar', 'HSS', 'GC'],
['Ashok Kumar Khatri', 'HSS', 'GC'],
['Ashok Kumar Khatri', 'HSS', 'GC'],
['Imad .', 'HSS', 'GC'],
['Imad .', 'HSS', 'GC'],
['Faiza .', 'LAW', 'LAW'],
['Madiha Talat', 'LAW', 'LAW'],
['Aisha Ahmad', 'LAW', 'LAW'],
['Sarah Humayun', 'LAW', 'LAW'],
['Asad Farooq', 'LAW', 'LAW'],
['Faiza .', 'LAW', 'LAW'],
['Sheharyar Sikander Hamid', 'LAW', 'LAW'],
['Ahmed Hasan Khan', 'LAW', 'LAW'],
['Nida Aftab', 'LAW', 'LAW'],
['Syed Zainuddin Moulvi', 'LAW', 'LAW'],
['Marva Khan', 'LAW', 'LAW'],
['Adnan Sattar', 'LAW', 'LAW'],
['Saad Amir', 'LAW', 'LAW'],
['Tariq Qazi', 'LAW', 'LAW'],
['Akhtar Ali', 'LAW', 'LAW'],
['Asim Zulfiqar Ali', 'LAW', 'LAW'],
['Hiba Akbar', 'LAW', 'LAW'],
['Summaiya Zaidi', 'LAW', 'LAW'],
['Ayesha Alam Malik', 'LAW', 'LAW'],
['Adnan Sattar', 'LAW', 'LAW'],
['Aisha Ahmad', 'LAW', 'LAW'],
['Maria Farooq', 'LAW', 'LAW'],
['Fahad Malik', 'LAW', 'LAW'],
['Syeda Zehra Zaidi', 'LAW', 'LAW'],
['Muhammad Umer Akram Chaudhry', 'LAW', 'LAW'],
['Sadaf Aziz', 'LAW', 'LAW'],
['Marva Khan', 'LAW', 'LAW'],
['Asad Rahim Khan', 'LAW', 'LAW'],
['Sikandar Ahmed Shah', 'LAW', 'LAW'],
['Muhammad Azeem', 'LAW', 'LAW'],
['Hammad Saeed', 'LAW', 'LAW'],
['Nida Iftikhar Paracha', 'LAW', 'LAW'],
['Uzair Kayani', 'LAW', 'LAW'],
['Muhammad Umar Ali', 'LAW', 'LAW'],
['Angbeen Atif Mirza', 'LAW', 'LAW'],
['Mariam Siddiq Alvi', 'SSE', 'MATH'],
['Imran Naeem', 'SSE', 'MATH'],
['Aftab Ali', 'SSE', 'MATH'],
['Masood Hussain Shah', 'SSE', 'MATH'],
['Asim Naseem', 'SSE', 'MATH'],
['Waqas Ali Azhar', 'SSE', 'MATH'],
['Imran Anwar', 'SSE', 'MATH'],
['Reza Abdolmaleki', 'SSE', 'MATH'],
['Ijaz Haider Naqvi', 'SSE', 'MATH'],
['Waqas Ali Azhar', 'SSE', 'MATH'],
['Ali Ashher Zaidi', 'SSE', 'MATH'],
['Shaheen Nazir', 'SSE', 'MATH'],
['Saad Qadeer', 'SSE', 'MATH'],
['Sultan Sial', 'SSE', 'MATH'],
['Haniya Azam', 'SSE', 'MATH'],
['Syed Moeez Hassan', 'SSE', 'MATH'],
['Choudhry Tanveer Shehzad', 'SDSB', 'BUSADM'],
['Muhammad Junaid Ashraf', 'SDSB', 'BUSADM'],
['Hassan Rauf Chaudhry', 'SDSB', 'BUSADM'],
['Muhammad Shehryar Shahid', 'SDSB', 'BUSADM'],
['Zehra Waheed', 'SDSB', 'BUSADM'],
['Muhammad Luqman Awan', 'SDSB', 'BUSADM'],
['Anjum Fayyaz', 'SDSB', 'BUSADM'],
['Sameen Zafar', 'SDSB', 'ACF'],
['Ummad Mazhar', 'SDSB', 'ACF'],
['Ummad Mazhar', 'SDSB', 'ACF'],
['Fareed Ud Din Farooq Qureshi', 'SDSB', 'ACF'],
['Mujeeb Rashid', 'SDSB', 'ACF'],
['Aneka Fahima Sufi', 'SDSB', 'ACF'],
['Shezeen Salim Hemani', 'SDSB', 'ACF'],
['Mehr Farhan Cheema', 'SDSB', 'ACF'],
['Afaf Khalid', 'SDSB', 'ACF'],
['Asif Iftikhar', 'SDSB', 'ACF'],
['Mohsin Bashir', 'SDSB', 'ACF'],
['Muhammad Ajmal', 'SDSB', 'ACF'],
['Sajid Siddique', 'SDSB', 'MGMTSCI'],
['Razi Allah Lone', 'SDSB', 'ACF'],
['Razi Allah Lone', 'SDSB', 'ACF'],
['Ali Nosherwan Hamed', 'SDSB', 'ACF'],
['Ali Sultan', 'SDSB', 'ACF'],
['Kamran Khan', 'SDSB', 'ACF'],
['Shireen Waheed', 'SDSB', 'MGMTSCI'],
['Salma Zaman', 'SDSB', 'ACF'],
['Areeb Abduhoo Pasha', 'SDSB', 'MGMTSCI'],
['Adnan Zahid', 'SDSB', 'MGMTSCI'],
['Salma Zaman', 'SDSB', 'ACF'],
['Sahar Arif', 'SDSB', 'ACF'],
['Muhammad Asim', 'SDSB', 'ACF'],
['Aaminah Zaman Malik', 'SDSB', 'ACF'],
['Khudejah Iqbal Ali', 'SDSB', 'ACF'],
['Muhammad Luqman Awan', 'SDSB', 'ACF'],
['Aleena Iqtidar', 'SDSB', 'ACF'],
['Saima Mujtaba Rana', 'SDSB', 'ACF'],
['Moeen Naseer Butt', 'SDSB', 'ACF'],
['Moeen Naseer Butt', 'SDSB', 'ACF'],
['Shoaib Amjad Hussain', 'SDSB', 'ACF'],
['Faiza Ali', 'SDSB', 'ACF'],
['Faiza Ali', 'SDSB', 'MGMTSCI'],
['Ashar Saleem', 'SDSB', 'MGMTSCI'],
['Amber Riaz', 'HSS', 'HSS'],
['Amber Riaz', 'HSS', 'HSS'],
['Basit Bilal Koshul', 'HSS', 'HSS'],
['Syed Sikander Gilani', 'HSS', 'HSS'],
['Tajdar Mufti', 'SSE', 'PHYSICS'],
['Muhammad Hamza Humayun', 'SSE', 'PHYSICS'],
['Adam Zaman Chaudhry', 'SSE', 'PHYSICS'],
['Rizwan Khalid', 'SSE', 'PHYSICS'],
['Ammar Ahmed Khan', 'SSE', 'PHYSICS'],
['Hafiz Muhammad Salman Rafi', 'HSS', 'POLSCI'],
['Rasul Bakhsh Rais', 'HSS', 'POLSCI'],
['Rida Ashfaq', 'HSS', 'POLSCI'],
['Taimur Rahman', 'HSS', 'POLSCI'],
['Adeel Hamza', 'HSS', 'POLSCI'],
['Ahmad Yunus Samad', 'HSS', 'POLSCI'],
['Umair Javed', 'HSS', 'POLSCI'],
['Farhat Haq', 'HSS', 'POLSCI'],
['Mohammad Waseem', 'HSS', 'POLSCI'],
['Syed Rashid Munir', 'HSS', 'POLSCI'],
['Shahid Malik', 'HSS', 'POLSCI'],
['Farhat Haq', 'HSS', 'POLSCI'],
['Arman Ashraf', 'HSS', 'HSS'],
['Yasser Hashmi', 'HSS', 'HSS'],
['Imran Rashid', 'HSS', 'HSS'],
['Yasser Hashmi', 'HSS', 'HSS'],
['Irfan Moeen Khan', 'HSS', 'HSS'],
['Mian Muhammad Nauman Faizi', 'HSS', 'HSS'],
['Amen Jaffer', 'HSS', 'HSS'],
['Hassan Rauf Chaudhry', 'SDSB', 'BUSADM'],
['Aneeqa Mazhar Wattoo', 'HSS', 'HSS'],
['Syed Javed Nazir', 'HSS', 'HSS'],
['Furrha Ahsan', 'HSS', 'HSS'],
['Syeda Habibah Hussain Rizvi', 'HSS', 'HSS'],
['Mahrukh Baig', 'HSS', 'HSS'],
['Faiza Asghar Dar', 'HSS', 'HSS'],
['Muhammad Hashim Kaleem Bhatti', 'HSS', 'HSS'],
['Zainab Sattar', 'HSS', 'HSS'],
['Huda Imtiaz', 'HSS', 'HSS'],
['Farhana Shahzad', 'HSS', 'HSS'],
['Afsheen Salahuddin', 'HSS', 'HSS'],
['Uzma Safdar', 'HSS', 'HSS'],
['Aamna Khalid', 'HSS', 'HSS'],
['Hajra Ikram Butt', 'HSS', 'HSS'],
['Baqar Hassan Syed', 'HSS', 'HSS'],
['Aurangzeb Haneef', 'HSS', 'HSS'],
['Essam Fahim', 'HSS', 'HSS'],
['Faaria Khan', 'HSS', 'HSS'],
['Muhammad Nawfal Saleemi', 'HSS', 'HSS'],
['Ali Usman Qasmi', 'HSS', 'HSS'],
['Muhammad Saad Imtiaz', 'HSS', 'HSS'],
['Muhammad Salaar Arif Khan', 'HSS', 'HSS'],
['Syed Javed Nazir', 'HSS', 'HSS'],
['Aamna Khalid', 'HSS', 'HSS'],
['Muhammad Saad Imtiaz', 'HSS', 'HSS'],
['Muhammad Haider Awan', 'HSS', 'SWR'],
['Amir Hussain', 'HSS', 'SWR'],
['Rabia Yasin', 'HSS', 'SWR'],
['Bashir Khalida', 'HSS', 'SWR'],
['Rashid Ahmad', 'HSS', 'SWR'],
['Azmat Ullah', 'HSS', 'SWR'],
['Nimra Nimra', 'HSS', 'SWR'],
['Kausar Farooq', 'HSS', 'SWR'],
['Muhammad Bilal Iqbal Khan', 'HSS', 'SWR'],
['Aruba Naz', 'HSS', 'SWR'],
['Shabana Kausar', 'HSS', 'SWR'],
['Mudassar Naseer', 'HSS', 'SWR'],
['Muhammad Shakeel', 'HSS', 'SWR'],
['Kanwal Yousaf', 'HSS', 'SWR'],
['Mohsin Riaz', 'HSS', 'SWR'],
['Babar Asad Khan', 'HSS', 'SWR'],
['Muhammad Shehryar Shahid', 'SDSB', 'BUSADM'],
['Shezeen Salim Hemani', 'SDSB', 'BUSADM']]